name: Helm-release Preparation.

on:
  workflow_call:
    inputs:
      REPO_URL:
        description: '<github-account-name>/<repo-name>'
        required: true
        type: string
      REPO_BRANCH:
        description: 'Repo Branch'
        required: true
        type: string
      CHART_VERSION:
        description: 'Version to update in Chart.yaml files'
        required: false
        type: string
      OLD_TAG:
        description: 'Old tag to replace in values.yaml (e.g., tag: develop)'
        required: false
        default: 'tag: develop'
        type: string
      NEW_TAG:
        description: 'New tag to replace in values.yaml (e.g., tag: 1.0.0)'
        required: true
        default: 'tag: 1.0.0'
        type: string
      OLD_IMAGE:
        description: 'Old Docker image to replace (e.g., mosipqa/)'
        required: false
        type: string
      NEW_IMAGE:
        description: 'New Docker image to replace with (e.g., mosipid/)'
        required: false
        type: string
      BASE:
        description: 'base branch for PR'
        required: true
        type: string
      COMMIT_MESSAGE:
        description: 'commit message'
        required: false
        type: string
    secrets:
      ACTION_PAT:
        required: true

jobs:
  helm-release-preparation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ inputs.REPO_URL }}
          ref: ${{ inputs.REPO_BRANCH }}

      - name: Install yq
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.30.8/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq
  
      - name: Find and update all values.yaml files
        run: |
          new_tag="${{ github.event.inputs.NEW_TAG }}"
          
          # Find all values.yaml files in the repository
          values_files=$(find . -name "values.yaml")
  
          if [ -z "$values_files" ]; then
            echo "No values.yaml files found in the repository."
            exit 1
          fi
  
          # Loop through each found values.yaml file and update it
          for file in $values_files; do
            echo "Processing $file"
            
            # Replace any prefix before the '/' in the repository field with 'mosipid'
            yq eval '.image.repository |= sub("^[^/]+", "mosipid")' -i "$file"
          
            # Replace the tag with the provided input
            yq eval ".image.tag = \"$new_tag\"" -i "$file"
  
            echo "Updated $file"
          done

          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6.1.0
        with:
          commit-message: Updated chart versions, image and tag for release changes
          title: ${{ github.event.inputs.COMMIT_MESSAGE }}
          body: Automated PR for release.
          branch: releas-branch
          delete-branch: true
          base: ${{ github.event.inputs.BASE }}
          token: ${{ secrets.ACTION_PAT }}
          signoff: true
          
